### ISSUE TITLE
[Bug Report] Object(...) is not a function，when upgrade to 1.1.0-beta.8

### ISSUE THREAD

**Issue by scjmjy** [element-plus/element-plus#3209]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
 windows/chrome 95.0.4628.3

### Vue version
3.1.5

### Reproduction Link
https://github.com/

### Steps to reproduce
1. step1, previous version: "element-plus": "^1.0.2-beta.70"
2. step2, upgrade to "1.1.0-beta.8": $yarn upgrade element-plus@latest
3. step3, modify my element-variables.scss file
-- $--font-path: "~element-plus/lib/theme-chalk/fonts";
-- @import "~element-plus/packages/theme-chalk/src/index";
++ $--font-path: "~element-plus/theme-chalk/fonts";
++ @import "~element-plus/theme-chalk/src/index.scss";

### What is Expected?
No errors occur.

### What is actually happening?
index.js?394a:243 Uncaught TypeError: Object(...) is not a function
    at eval (index.js?394a:243)
    at Module../node_modules/element-plus/es/components/autocomplete/index.js (chunk-vendors.js:3702)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at eval (component.js?47b3:1)
    at Module../node_modules/element-plus/es/component.js (chunk-vendors.js:3666)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at eval (defaults.js?1250:1)
    at Module../node_modules/element-plus/es/defaults.js (chunk-vendors.js:4542)

Relative file:
webpack-internal:///./node_modules/element-plus/es/components/autocomplete/index.js
line 257:
const _hoisted_3 = /* @__PURE__ */ Object(vue__WEBPACK_IMPORTED_MODULE_0__["createElementVNode"])("i", { class: "el-icon-loading" }, null, -1);

**Comment by scjmjy** [comment]
Well, this problem is resolved by upgrading vue to 3.2.0+

**Comment by scjmjy** [comment]
Well, this problem is resolved by upgrading vue to 3.2.0+
